dataset:
  pdb_paths:
    - ./demo/data/8u4r_chothia.pdb
  tgt_chains:
    - R
  lig_chains:
    - HL

templates:
  # antibody (requires a pre-docked antigen-framework complex)
  - class: Antibody
    cdr_type: HCDR3


batch_size: 16
n_samples: 50  # 50 candidates for each complex